/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/tpatki/local/src/slurm-test/sim_test_dir/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/home/tpatki/local/src/slurm-test/sim_test_dir/slurm_conf/slurm.conf";
char *default_plugstack = "/home/tpatki/local/src/slurm-test/sim_test_dir/slurm_conf/plugstack.conf";
